POST http://localhost:3333/api/testes
Content-Type: application/json

{
    "prompt": "Como está o tempo hoje?"
}

###

POST http://localhost:3333/animals
Content-Type: application/json

{
    "animals": ["Elefante", "Tigre", "Bicho-pau"]
}

###

POST http://localhost:3333/user
Content-Type: application/json

{
    "fullName": "Clebson", "phone": "22", "password": "4321"
}

###

POST http://localhost:3333/login
Content-Type: application/json

{
    "phone": "22", "password": "4321"
}

