POST http://localhost:3333/api/testes
Content-Type: application/json

{
    "prompt": "Como está o tempo hoje?"
}

###

POST http://localhost:3333/animals
Content-Type: application/json

{
    "animals": ["Elefante", "Tigre", "Bicho-pau"]
}

###

POST http://localhost:3333/animals/destroy

###


POST http://localhost:3333/user
Content-Type: application/json

{
    "fullName": "Clebson", "phone": "22", "password": "4321"
}

###

POST http://localhost:3333/login
Content-Type: application/json

{
    "phone": "22", "password": "4321"
}

###

POST http://localhost:3333/animals/create
Content-Type: application/json

{
      "name": "Leão",
      "characteristics": {
        "Habitat": "Savana, florestas e pradarias",
        "Filo": "Chordata",
        "Estado de conservação": "Vulnerável",
        "Dieta": "Carnívoro",
        "Método de reprodução": "Sexuado",
        "Classe": "Mammalia"
      }
}


###

POST http://localhost:3333/games/12
Content-Type: application/json

###

POST http://localhost:3333/games/localhost:3333/games/update
Content-Type: application/json

{
    "id": "bf0849fc-217a-4f0c-910a-38d1ab95535e",
    "userId": 284,
    "animalId": 408
}


### 

POST http://localhost:3333/games/update
Content-Type: application/json

{
  "id": "bf0849fc-217a-4f0c-910a-38d1ab95535e",
  "animalId": 413,
  "userId": 284,
}
